# Generated by Django 4.2.2 on 2023-06-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_word_delete_words'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Words',
        ),
    ]
