# Generated by Django 4.2.2 on 2023-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('gender', models.CharField(choices=[('der', 'Der'), ('dir', 'Dir'), ('das', 'Das')], max_length=3, verbose_name='Gender')),
            ],
        ),
        migrations.DeleteModel(
            name='Words',
        ),
    ]
