# Generated by Django 4.2.2 on 2023-06-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_words_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('gender', models.CharField(choices=[('dir', 'Dir'), ('das', 'Das'), ('der', 'Der')], max_length=3, verbose_name='Gender')),
            ],
        ),
        migrations.DeleteModel(
            name='Words',
        ),
    ]
